name: leviticus
description: Primeiro incremento de Pessoas do O.S. Shepherd.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_app_check: ^0.4.8
  cupertino_icons: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
